### PR TITLE
Splits reporting into frontend and backend implementation

### PR DESCRIPTION
**Pull request by eyck**
This should address #10

### CODE REVIEW

**Comment by eyck** [comment]
Unfortunatly the style checker uses clang-format 10.0 which is not available in newer Ubuntu releases. So '#23 should be implemented to easily allow contributions.

**Comment by markfoodyburton** [comment]
Overall this looks good to me.
I will try it out internally - if e.g. @aut0 is in agreement, we can merge here anyway

**Review by markfoodyburton — APPROVED** [review]

**Comment by markfoodyburton** [comment]
Oh, there are missing libraries ! --- 

a) we need to tag the pervious version (!)
b) there are a bunch of fixes to the library, and we'll need to make changes to our code too..

I'll revert for now and fix on Monday :-(

**Comment by eyck** [comment]
Which libraries are missing?

**Pull request merged**
